/** Event Constants */
export const Events = {
  STATE_CHANGED: 'state:changed',
  CONFIG_LOADED: 'config:loaded',
  MAPPINGS_LOADED: 'mappings:loaded',
  CELL_PROCESSING_STARTED: 'cell:processing:started',
  CELL_PROCESSING_COMPLETE: 'cell:processing:complete',
  CELL_PROCESSING_ERROR: 'cell:processing:error',
  CELL_SELECTED: 'cell:selected',
  CANDIDATES_AVAILABLE: 'candidates:available',
  HISTORY_CACHE_INITIALIZED: 'history:cache:initialized',
  SERVER_STATUS_CHANGED: 'server:status:changed',
  SERVER_RECONNECTED: 'server:reconnected',
  TRACKING_STARTED: 'tracking:started',
  TRACKING_STOPPED: 'tracking:stopped',
  SETTING_CHANGED: 'setting:changed',
  NORMALIZATION_METHOD_CACHE: 'normalization:method:cache',
  NORMALIZATION_METHOD_FUZZY: 'normalization:method:fuzzy',
  NORMALIZATION_METHOD_LLM: 'normalization:method:llm',
  NORMALIZATION_NO_MATCH: 'normalization:no:match',
  CACHE_HIT: 'cache:hit',
  CACHE_MISS: 'cache:miss',
};
